### ISSUE TITLE
gfw.press安裝腳本，gfw.press和3proxy登記成為系統服務

### ISSUE THREAD

**Issue by twfcc** [chinashiyu/gfw.press#12]
適用於debian 7/8 和 ubuntu 14.4/15.04，腳本下載
https://raw.githubusercontent.com/twfcc/gfw.press_installer/master/gfw3proxy_init.sh

安裝完成預設一個用戶，並會給出資訊，gfw.press啟動腳本存放在 /etc/init.d/
用法

/etc/init.d/gfw.press start | stop | restart | status

3porxy 啟動腳本使用

/etc/init.d/3proxyinit start | stop

兩者的目錄gfw.press和3proxy,均放到 /usr/local/etc/ ，須要改動gfw.press/user.txt 或 3proxy/3proxy.cfg
可在那裡找到

**Comment by AmberisMyShiba** [comment]
运行后出现如下错误。
sh gfw3proxy_init.sh
gfw3proxy_init.sh: 29: [: -ne: unexpected operator
gfw3proxy_init.sh: 36: gfw3proxy_init.sh: Syntax error: Bad function name

**Comment by twfcc** [comment]
你是否複制黏貼代碼?試試在vps上以root執行
wget --no-check-certificate https://raw.githubusercontent.com/twfcc/gfw.press_installer/master/gfw3proxy_init.sh

chmod +x gfw3proxy_init.sh && ./gfw3proxy_init.sh

sh 不一定是bash,debian 的/bin/sh是 dash，沒有bash的特性

**Comment by AmberisMyShiba** [comment]
谢谢回复，可以了。

2016-08-02 14:38 GMT+08:00 Victor Fung notifications@github.com:

**Comment by twfcc** [comment]
😀
