### ISSUE TITLE
求个船票，破船上不去啊

### ISSUE THREAD

**Issue by pwash** [chinashiyu/gfw.press#16]
卧槽 刚发完刷了

**Comment by jzp820927** [comment]
刚发完刷了？啥意思？

**Comment by pwash** [comment]
昨天网站上好像放出几百个船票

**Comment by jzp820927** [comment]
几百个？我去，这是要搞大狂欢的节奏啊。

**Comment by pwash** [comment]
不用太担心 瞬间就完了

石斑鱼大爷 ‏@chinashiyu  17小时17小时前 
http://GFW.Press  

翻墙大杀器上线两个月纪念，放码200个 

http://gfw.press/code.php
