### ISSUE TITLE
对比VPN,getlantern,shadowsocks有什么优势？

### ISSUE THREAD

**Issue by figofuture** [chinashiyu/gfw.press#3]
原理是啥？对比VPN, getlantern还有shadowsocks这些神器有啥优势？

**Comment by lyx32** [comment]
这个是原理
https://medium.com/@FWTO_O/gfw-press%E6%BA%90%E7%A0%81%E7%AE%80%E6%9E%90-61a2714eb99f#.2pr7bbg7p
优势的话，目前不清楚，可能是安全吧

**Comment by chinashiyu** [comment]
在服务端，相同的连接用户，shadowsocks的CPU使用率100%，GFW.Press是2%，并且shadowsocks只能用到一个核。

**Comment by fudingyu** [comment]
我想大家问的意思更关心的不是CPU使用性能，而是抗墙性吧。

所以在抗攻击方面有些什么优势呢？相比起上述的几个

**Comment by chinashiyu** [comment]
你都代表大家了，那你有没有三个代表呢

**Comment by fudingyu** [comment]
没有代表大家，我只是在猜测用户关心的问题。当然我的猜测有可能对，有可能不对。这无关紧要。

请直接回答我的问题吧“所以在抗攻击方面有些什么优势呢？相比起上述的几个”

**Comment by fudingyu** [comment]
没有代表大家，我只是在猜测用户关心的问题。当然我的猜测有可能对，有可能不对。这无关紧要。

请直接回答我的问题吧“所以在抗攻击方面有些什么优势呢？相比起上述的几个”

**Comment by keysona** [comment]
@chinashiyu 
ss的cpu使用率没有这么高吧.
我特地找3个人测试了下。
都开1080p。
然后看top，ssserver -- cpu -- 2%，内存 -- 2%。

这是python版的。

早期ss貌似也是这种线程并发模型，后来为了性能提升，采用了epoll模型。只看了最新版的源码。
尽管是单线程，但是效率惊人。所花的cpu，内存也很少。

这也是为什么搬瓦工的廉价vps能够流行的原因了。

相比下，我觉得这个项目更适合作为源码教学。
因为代码可读性太强了。ss的源码读得很蛋疼。

要跑起这个，vps的配置就要很高了，比如内存1g，基本上都用来跑这个了....

相对的，ss的内存，cpu使用根本是可以忽略不计了....

日后提升性能的话，是否会采用ss一样的模型？尽管ss不支持多核，但我个人认为足够了。要支持的话我觉得也很容易，参照nginx的master/slave，不过原作者没有采用这种做法的话，我猜测这种单线程做法足够了。

对于个人站长，一台vps上跑个ss加个小站完全没问题了。


关于数据包的加密解密，我对这个不是很了解。

混淆/加密都是为了避开防火墙的触发机制。

然后，到目前为止，防火墙并没有封杀掉ss，只能找作者喝茶，让他停止开发。

我觉得这是一个暗示了。ss的协议是可以的。

**Comment by chinashiyu** [comment]
参考 https://github.com/chinashiyu/gfw.press/blob/master/tech.png
