### ISSUE TITLE
can not use gfw.press in Windows 10 home edition

### ISSUE THREAD

**Issue by jdhao** [chinashiyu/gfw.press#34]
I am using Windows 10(64 bit)home edition. After I installed the gfw.press msi file, the **clien.bat** can not be executed by double-clicking on it. The command line window just poped up and disappeared quickly. 

I have alao installed gfw.press in my Windows 8.1 computer, and it works nicely. So maybe there are some
compatibility problems which prevent this software from working with Windows 10 properly.

**Comment by jzp820927** [comment]
试试 管理员权限 运行

**Comment by jdhao** [comment]
@jzp820927, I have tried to run it using administrator priviledge, but to no avail. The result is just the same.

**Comment by jzp820927** [comment]
是不是没装 java 环境？

**Comment by jdhao** [comment]
@jzp820927 , maybe, it is my friend's computer , so I am not sure whether java runtime is installed or not. I will check it to see if that is the problem.

**Comment by jzp820927** [comment]
cmd ，运行  java -version ，如果有输出版本号，说明安装了，如果没有任何输出，说明没安装，你试试就知道了。

**Comment by chinashiyu** [comment]
已自带JRE。
不要安装在带空格的目录。
用兼容方式运行试试。

**Comment by jdhao** [comment]
@chinashiyu ， I put the installed file under a folder without blank space, now it can run

**Comment by jzp820927** [comment]
原来是路径不能带空格
