### ISSUE TITLE
有的网站无法打开，提示“你所请求的网址无法获取“

### ISSUE THREAD

**Issue by jdhao** [chinashiyu/gfw.press#37]
如题，使用gfw.press的代理服务器以后，有的网站打开的时候会提示”你所请求的网址无法获取“，完整错误提示如下：

> 当尝试取回该 URL 时遇到下面的错误：http://blog.sina.com.cn/s/blog_bd3e97870101x6lc.html
> 读取错误
> 系统返回以下内容：(104) Connection reset by peer
> An error condition occurred while reading data from the network. Please retry your request.
> 缓存服务器的管理员 webmaster@gfw.press.

如果关闭代理服务器，这些网站又可以正常打开了，请问可能是什么原因，如何解决？

**Comment by jzp820927** [comment]
可能是服务端限制了 代理访问国内网站
