### ISSUE TITLE
SPAM

### ISSUE THREAD

**Issue by chonion** [chinashiyu/gfw.press#39]
這個軟件沒有任何優勢，而且作者用了大量的推特帳號相互吹捧。
當然了，欺騙豬國人沒有問題，所以作者根本不敢用英文來介紹。

**Comment by chonion** [comment]
所有攻擊性的回覆，都是同一個帳號。
請作者正面回答問題，有本事告訴大家你的代碼做了什麼。哪裡來的『軍用』，什麼軍？

**Comment by chonion** [comment]
如果是正經的軟件，用得著這麼偷偷摸摸嗎？

**Comment by chonion** [comment]
我猜想這個片子帳號，不會有任何其他的開發了。 
真正的軟件，是不斷的開發過程，而且有其他開發者的同步

**Comment by chonion** [comment]
看著這個repo滿多的Star 和Fork，而且大多是豬國的程序員，你就知道在豬國騙子真的不夠用

**Comment by sutun2008** [comment]
何出此言？只要别留后门就好

**Comment by yiguihai** [comment]
反正没骗我钱还能翻墙管他呢

**Comment by weaming** [comment]
你看得懂代码吗，你找出后门了吗

**Comment by hanlray** [comment]
刚才发现用这个程序做http proxy下载的东西md5总是校验失败，换别的proxy就没问题，不知道是不是程序的问题

**Comment by qwe14789cn** [comment]
免费的代理多了去了
有这个时间在这里哔哔不如自己搭建个vps，浪费时间

**Comment by xpirad** [comment]
@chonion 你是猪吧 :)

**Comment by theratlesnake** [comment]
楼主回家给你妈收尸吧。
