### ISSUE TITLE
虽然windows版速度慢了点，不过支持一下

### ISSUE THREAD

**Issue by theratlesnake** [chinashiyu/gfw.press#42]
宽带是电信的，虽然gfw慢了点，不过石大爷为大家开发的软件而且还免费，我们使用的人也该感谢一下石大爷，另外，那些骂人的脑里在想什么？

**Comment by jzp820927** [comment]
用户量大，肯定就慢了，本来就是开放注册的，又没限制。

**Comment by theratlesnake** [comment]
@jzp820927 哈，大神又见到你了。

![2345 20170104151857](https://cloud.githubusercontent.com/assets/24611087/21634295/1229f4ce-d291-11e6-8a43-2862b69aa5b3.jpg)

我想问下，这几行是什么意思哦？

**Comment by jzp820927** [comment]
配置域名规则，根据这个规则来选择代理。

**Comment by theratlesnake** [comment]
@jzp820927 例如我要在xx里把github加入到一打开网站就自动代理，要怎么添加呢？求解

**Comment by jzp820927** [comment]
1，2句话说不清楚，google 搜索 “SwitchyOmega 规则 配置”，一大堆图文教程教你怎么做

**Comment by theratlesnake** [comment]
@jzp820927 好

**Comment by guoyan1983** [comment]
不知道国内的某项政策会不会影响gfwpress

**Comment by guoyan1983** [comment]
不知道国内的某项政策会不会影响gfwpress

**Comment by jzp820927** [comment]
什么ZC，说明白点
