### ISSUE TITLE
使用谷歌时候频繁出现recaptcha 

### ISSUE THREAD

**Issue by jdhao** [chinashiyu/gfw.press#46]
最近使用 gfw.press 的时候频繁引发谷歌 recaptcha，什么原因？以前好像没怎么遇到过这种情况啊

**Comment by jzp820927** [comment]
估计是使用人数太多，触发了 google 的异常流量验证。可以换个服务器试试。

**Comment by jdhao** [comment]
@jzp820927 , 换了提供的三个 ip 的另外一个，现在暂时不出现 recaptcha 了。

**Comment by jzp820927** [comment]
一旦某个 IP 被大量人使用访问 google 就有可能触发 google 的异常流量验证，被 google 判断为 大流量攻击，所以。。。。

**Comment by jdhao** [comment]
更换 ip 有作用。
