### ISSUE TITLE
SPAM

### ISSUE THREAD

**Issue by jdhao** [chinashiyu/gfw.press#48]
感觉软件最近不太管用了，明明已经设置好了，但是使用谷歌搜索的时候还是不行，经常是能够打开谷歌页面，一搜索东西，就“访问的页面出错了”。
我的服务器ip，端口号，本地端口号设置都是没问题的，已经 cross check 了好多遍了。

**Comment by jzp820927** [comment]
换个服务器试试？

**Comment by jdhao** [comment]
现在就提供两个地址，我都试了，不稳定，经常上不了谷歌
