### ISSUE TITLE
WLAN被关闭

### ISSUE THREAD

**Issue by ghost** [chinashiyu/gfw.press#63]
每次打开和关闭大杀器的时候 WiFi 都会断开，而且没有其它反应也不能翻墙。

**Comment by CaKrome** [comment]
Android版GFW.Press是通过系统代理实现翻墙，
https://gfw.press/blog/?p=68
请按照教程设置代理

**Comment by xsfzwmh** [comment]
哥们，能否私信一个最新可用的节点呀，谢谢了。19341987@qq.com
